### ISSUE TITLE
Set mob texture

### ISSUE THREAD

**Issue by LordSim0n** [leMaik/RpgPlus#52] opened 2016-05-18 18:31 UTC
Maybe it would be helpful if we could set the texture of a mob which we spawn to get skeleton-horses, killer-bunnys... or animals with exact textures.

**Comment by leMaik** [comment] 2016-05-18 22:44
I just added `color`, `style`, `variant`, `jumpStrength`, `domestication` and `maxDomestication` properties to horses. You can specify them when spawning horses or get/set them later (i.e. `horse.color = "brown"`). :smile: 

See [Bukkit Javadocs](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Horse.html) for possible values.

I'll implement more properties for rabbits soon. What do you mean by "or animals with exact textures"?

**Comment by LordSim0n** [comment] 2016-05-19 09:50
Umm... the value Ocelot.Type . :)

Is it already possible to set Horses, Ocelots and Wolfes tamed or an owner? 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Tameable.html#setTamed(boolean)

**Comment by leMaik** [comment] 2016-05-19 16:52
No, it's not yet possible to tame entities. The problem is that managed entities are removed when the server restarts, so they may not be as useful right now.
I'll add ocelot types later.

**Comment by leMaik** [comment] 2016-07-19 18:15
Okay, I finally implemented ocelot type. See #56 for tameable entities.

I'll close this now, but feel free to create new issues when entity types are missing.

**Closed by leMaik** 2016-07-19 18:15 UTC
Labels: enhancement, scripting
